# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 06:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminCuentas', '0003_auto_20170627_0614'),
        ('Noticias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='lector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Noticias.Lector'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AdminCuentas.Editor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noticia',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AdminCuentas.Categoria'),
            preserve_default=False,
        ),
    ]
