# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Noticias', '0003_auto_20170627_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='descripcion',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
