# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 06:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Noticias', '0001_initial'),
        ('AdminCuentas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='editores',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminCuentas.Editor'),
        ),
        migrations.AddField(
            model_name='editor',
            name='noticias',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Noticias.Noticia'),
        ),
    ]
