# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 06:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminCuentas', '0003_auto_20170627_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='editor',
            name='administrador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminCuentas.Admin'),
        ),
    ]
